# This requires substitutions or parameters on the cli

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  # platformio_options:
      # build_flags:
      # In addition to lilygo's settings:
      # To enable reading logs over USB until `hardware_uart: USB_CDC` support
      # is added to `logger:`, as detailed in <https://github.com/esphome/feature-requests/issues/1906>:
      # - "-DARDUINO_USB_MODE=1"
      # - "-DARDUINO_USB_CDC_ON_BOOT=1"
  on_boot: 
    then:
      - light.turn_off: espcam_flashlight

esp32:
  board: esp32cam
  framework:
    type: esp-idf 

# Enable SDCard reader on the esp32cam
external_components:
  - source: github://mnark/esphome-components
    components: [sdmmc]
    refresh: 1d

globals:
  - id: save_to_disk
    type: bool
    restore_value: no
    initial_value: "false"
  - id: filename
    type: std::string
    restore_value: no
    initial_value: '"img"'
  - id: filecount
    type: int
    restore_value: yes
    initial_value: "0"

debug:
  update_interval: 1h

# Enable logging
logger: 
  level: VERY_VERBOSE
  logs:
    esp32_camera: INFO
    esp32_camera_sd: INFO
    esp32_camera_sdmmc: INFO
    ota: INFO
    wifi: INFO    
    esp32_camera_web_server: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret hasskey

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret ssid
  password: !secret ssid_password

captive_portal:

esp32_camera:
  name: ${name}
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600
  jpeg_quality: 10
  on_image:
    then:
      - lambda: |-
          if (id(save_to_disk)) {
            id(sdcard1).write_file(id(filename).c_str(), image.length, image.data);
            id(save_to_disk) = false;
          }

esp32_camera_web_server:
  - port: 8080
    mode: stream
#  - port: 8081
#    mode: snapshot

output:
  - platform: ledc
    pin: GPIO4
    id: gpio_4
    channel: 2

light:
  - platform: monochromatic
    output: gpio_4
    name: "${friendly_name} Flashlight"
    restore_mode: ALWAYS_OFF
    id: espcam_flashlight

sdmmc:
  id: sdcard1
  name: "SD Card"
  command_pin: GPIO15
  clock_pin: GPIO14
  data_pin: GPIO02

button:
  - platform: restart
    name: "Restart"
  - platform: template
    id: save2card
    name: Save to Card
    on_press:
      then:
        - lambda: |-
            id(save_to_disk) = true;
            id(filecount)++;
            id(filename) = "file" + std::to_string(id(filecount)) + ".jpg";

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: debug
    free:
      name: "Heap Free"